
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2'

# do this before your build tasks
- task: DotNetCoreCLI@2
  displayName: restore packages
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Buid project
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need.

- task: DotNetCoreCLI@2
  displayName: publish exe
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) -r win10-x64'
    zipAfterPublish: True

